@ApiService_HostAddress = http://localhost:5575

GET {{ApiService_HostAddress}}/summarize?slug=whats-new/aspire-13/
Accept: application/json

###

POST {{ApiService_HostAddress}}/chat
Content-Type: application/json

{
  "message": "Hello, what can you tell me about .NET Aspire?"
}

###

GET {{ApiService_HostAddress}}/health
Accept: application/json
